version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - fsnet
  logstash:
    image: docker.elastic.co/logstash/logstash:8.12.0
    ports:
      - "5001:5001"
    networks:
      - fsnet
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.0
    ports:
      - "5601:5601"
    networks:
      - fsnet
networks:
  fsnet:
    driver: bridge
