name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y docker-compose curl
      - name: Build all images
        run: |
          sudo docker-compose -f docker/docker-compose.yml build
      - name: Linting
        run: |
          cd docker
          sudo docker run --rm -i hadolint/hadolint  < apache/dockerfile
          sudo docker run --rm -i hadolint/hadolint  < nginx/dockerfile
          sudo docker run --rm -i hadolint/hadolint  < pythonapi/dockerfile
      - name: Validate Compose config
        run: docker-compose -f docker/docker-compose.yml config
      - name: Test containers
        run: |
          sudo docker-compose -f docker/docker-compose.yml up -d
          sleep 10
          curl -i http://localhost
          curl -i http://localhost/api/health
      - name: Tag Docker images
        run: |
          sudo docker tag nginx:latest nginx:${{ github.sha }}
          sudo docker tag apache:latest apache:${{ github.sha }}
          sudo docker tag phthonapi:latest phthonapi:${{ github.sha }}
      - name: Auto-redeploy
        run: echo "Redeploy triggered on push to main"
